# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet pack --configuration $(buildConfiguration) src/FindRef.csproj
  displayName: 'Compile and pack'

- script: cp src/nupkg/*.nupkg '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy nupgk to artifacts staging'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: findrefNuget
